### ISSUE TITLE
Error CS0121

### ISSUE THREAD

**Issue by gabriella-guimaraes** [gabriella-guimaraes/ControleFinanceiro#2]
Erro ao gerar o Controller:

error CS0121: A chamada é ambígua entre os seguintes métodos ou propriedades: "Microsoft.Extensions.DependencyInjection.IdentityServiceCollectionExtensions.AddIdentity<TUser, TRole>(Microsoft.Extensions.DependencyInjection.IServiceCollection)" e "Microsoft.Extensions.DependencyInjection.IdentityServiceCollectionExtensions.AddIdentity<TUser, TRole>(Microsoft.Extensions.DependencyInjection.IServiceCollection)"
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)

![image](https://user-images.githubusercontent.com/71671440/181651770-e9e8c5ee-d9df-4421-b0e9-bcb0f29b3d90.png)

**Comment by gabriella-guimaraes** [comment]
- Downgrade dos pacotes Entity Framework - 6.0.7 para 3.1.15. Novos erros ao compilar:
![image](https://user-images.githubusercontent.com/71671440/181656855-26108d51-b075-44a7-ad0a-9a2171e258e8.png)
